### PR TITLE
[WIP] revise documentation for new polygonal/polyhedral layout

### PR DESCRIPTION
**Pull request by xjrc**
The changes in this pull request revise the Conduit documentation to reflect the new polygonal/polyhedral layout presented in [CON-504](https://github.com/LLNL/conduit/issues/504). The following items need to be completed before this pull request can be merged:

- [x] Update the high-level description for the polygonal/polyhedral topological schemas.
- [x] Update the rudimentary examples for the polygonal/polyhedral schemas.

### CODE REVIEW

**Comment by xjrc** [comment]
@bmhan12: Let me know once you have a working version of `to_polygonal` for polyhedral topologies; I'd like to use it to update the `blueprint_demo_basic_polyhedra` demo in [`t_conduit_docs_blueprint_demos.cpp`](https://github.com/LLNL/conduit/blob/master/src/tests/docs/t_conduit_docs_blueprint_demos.cpp#L582).

**Comment by bmhan12** [comment]
@xjrc I just force pushed the branch with a `to_polygonal()` version for polyhedral. Let me know if anything is amiss.

**Comment by xjrc** [comment]
@bmhan12: Thanks! It looks like your changes in f553cae preemptively addressed the second part of my documentation update, so the documentation side of things looks to be ready whenever you are!

**Review by bmhan12 — APPROVED** [review]
Thanks @xjrc ! LGTM! I've rebased my branch a few times, so there are some merge conflicts, but once those are resolved I can merge this!

**Comment by xjrc** [comment]
@bmhan12: I've updated my branch to resolve the conflicts (it looks like they were just conflicts between older and newer iterations of your code), so please feel free to merge whenever you're ready.

**Pull request merged**
